### DISCUSSION TITLE
Profiles : IAudioDecoderManager.yaml

### DISCUSSION THREAD

**Discussion by Ulrond** [rdkcentral/rdk-halif-aidl#2] [Ideas]
## IAudioDecoderManager.yaml

```yaml
IAudioDecoderManager:  # Component object begins
    interfaceVersion: 1         # Integer value
    IAudioDecoder:              # Resource list
      - 0:
        supportedCodecs:        # Array of codec capabilities
          - AAC_LC
          - HE_AAC
          - HE_AAC2
          - DOLBY_AC3
          - DOLBY_AC3_PLUS
          - DOLBY_AC3_PLUS_JOC
          - DOLBY_AC4
          - X_HE_AAC
        supportsSecure: true
      - 1:                   # Resource object begins
        supportedCodecs:        # Array of codec capabilities
          - AAC_LC
          - HE_AAC
          - HE_AAC2
          - DOLBY_AC3
          - DOLBY_AC3_PLUS
          - DOLBY_AC3_PLUS_JOC
          - DOLBY_AC4
          - X_HE_AAC
        supportsSecure: true
```

access rights to get this as an example

To list the supported codecs for audio decode 0, or 1

- `IAudioDecoderManager.IAudioDecoder.0.supportedCodecs`
- `IAudioDecoderManager.IAudioDecoder.1.supportedCodecs`
